- name: Install Wazuh Agent on Linux Servers
  hosts:
    - web-server
    - db-server
    - ldap-server
  become: true
  vars:
    wazuh_manager_ip: "{{ hostvars['siem-server']['ansible_host'] }}"
  tasks:
    - name: Add Wazuh repository GPG key
      shell: |
        curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
      args:
        warn: no
      when: ansible_os_family == "Debian"

    - name: Add Wazuh repository
      apt_repository:
        repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Wazuh agent
      package:
        name: wazuh-agent
        state: present

    - name: Configure Wazuh agent
      lineinfile:
        path: /var/ossec/etc/ossec.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '<address>.*</address>', line: '<address>{{ wazuh_manager_ip }}</address>' }
        - { regexp: '<server-ip>.*</server-ip>', line: '<server-ip>{{ wazuh_manager_ip }}</server-ip>' }
      notify: restart wazuh-agent

    - name: Register Wazuh agent with the manager
      command: >
        /var/ossec/bin/agent-auth -m {{ wazuh_manager_ip }}
      args:
        creates: /var/ossec/etc/client.keys

    - name: Start and enable Wazuh agent
      service:
        name: wazuh-agent
        state: started
        enabled: yes

  handlers:
    - name: restart wazuh-agent
      service:
        name: wazuh-agent
        state: restarted
